name: Azure Deploy Backend

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      source_tag:
        description: "Tag de origem para promoção"
        required: false
        default: "stag"
      target_tag:
        description: "Tag de destino (promoção)"
        required: false
        default: "prod"

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: promozone-backend
  PROD_TAG: prod
  STAG_TAG: stag
  ACR_NAME: promozone
  RG: promozone-prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build backend image
        working-directory: backend
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI - Fetch ACR info
        id: acr
        run: |
          LOGIN_SERVER=$(az acr show --name "${{ env.ACR_NAME }}" --resource-group "${{ env.RG }}" --query loginServer -o tsv)
          echo "login_server=$LOGIN_SERVER" >> $GITHUB_OUTPUT

      - name: ACR login
        run: |
          az acr login --name "${{ env.ACR_NAME }}"

      - name: Tag and push image to ACR
        run: |
          LOGIN_SERVER='${{ steps.acr.outputs.login_server }}'
          GIT_SHA=${GITHUB_SHA::7}
          docker tag $IMAGE_NAME:latest $LOGIN_SERVER/$IMAGE_NAME:${{ env.STAG_TAG }}
          docker tag $IMAGE_NAME:latest $LOGIN_SERVER/$IMAGE_NAME:$GIT_SHA
          docker push $LOGIN_SERVER/$IMAGE_NAME:${{ env.STAG_TAG }}
          docker push $LOGIN_SERVER/$IMAGE_NAME:$GIT_SHA

  promote:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI - Fetch ACR info
        id: acr
        run: |
          LOGIN_SERVER=$(az acr show --name "${{ env.ACR_NAME }}" --resource-group "${{ env.RG }}" --query loginServer -o tsv)
          echo "login_server=$LOGIN_SERVER" >> $GITHUB_OUTPUT

      - name: Promote tag in ACR
        run: |
          LOGIN_SERVER='${{ steps.acr.outputs.login_server }}'
          az acr import \
            --name "${{ env.ACR_NAME }}" \
            --source "$LOGIN_SERVER/${{ env.IMAGE_NAME }}:${{ inputs.source_tag }}" \
            --image "${{ env.IMAGE_NAME }}:${{ inputs.target_tag }}"