name: Deploy Backend

on:
  push:
    paths:
      - "backend/**"
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag da imagem para deploy"
        required: false
        default: "latest"

env:
  AWS_REGION: eu-west-1
  ECR_REPO: promozone-backend
  ECS_CLUSTER: promozone-cluster
  ECS_SERVICE: promozone-svc

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Debug OIDC Token
        run: |
          echo "Solicitando token..."
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                      "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')

          echo "Decodificando payload:"
          echo $TOKEN | cut -d "." -f2 | base64 -d | jq .
        shell: bash

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-backend-deploy
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
          output-credentials: true
        env:
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push image
        run: |
          set -e
          ECR_URI=$(aws ecr describe-repositories --repository-names "$ECR_REPO" --query 'repositories[0].repositoryUri' --output text --region "$AWS_REGION")
          docker build -t "$ECR_REPO" backend/
          docker tag "$ECR_REPO:latest" "$ECR_URI:latest"
          docker push "$ECR_URI:latest"

      - name: Force new ECS deploy
        run: |
          aws ecs update-service \
            --cluster "$ECS_CLUSTER" \
            --service "$ECS_SERVICE" \
            --force-new-deployment \
            --region "$AWS_REGION"
